### ISSUE TITLE
Wrapwidth affects both lines and occurence list, possible to separate?

### ISSUE THREAD

**Issue by izimobil** [izimobil/polib#82]
Originally reported by: **Ilya Ivanov (Bitbucket: [sexydev](https://bitbucket.org/sexydev), GitHub: [sexydev](https://github.com/sexydev))**

----------------------------------------

When file is opened/saved like ```po = polib.pofile(po_file,wrapwidth=999999)```, that affects both actual lines and occurence list:
```
#: english/text/english/dialog/newr1.msg:423 english/text/english/game/perk.msg:205
msgid "Stonewall"
msgstr "Muro de piedra"
```
However, msgcat (from translate-toolkit), when passed "--no-wrap" option, only applies it to msgid/msgstr, not occurences:
```
#: english/text/english/dialog/newr1.msg:423
#: english/text/english/game/perk.msg:205
msgid "Stonewall"
msgstr "Muro de piedra"
```
As far as I can tell, both formats are correct, but the problem is that you use both msgcat and another, polib-based tool to work with files without wrapping, it results in large amount of senseless diffs.
It would probably be helpful to have another open flag, which would make the output uniform with msgcat?

----------------------------------------
- Bitbucket: https://bitbucket.org/izi/polib/issue/82

**Comment by Carloswaldo** [comment]
I'm sorry for reopening this issue but I got into the same issue and I'd like to clarify this is not a translate toolkit issue, it's the actual behaviour of gettext.

This is what [the xgettext manual](https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html) says:

```
‘--no-wrap’
Do not break long message lines. Message lines whose width exceeds the output page width will not be split into several lines. Only file reference lines which are wider than the output page width will be split.
```

A real world example: let's take the [initdb.c file from the PostgreSQL project](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/bin/initdb/initdb.c;h=152d21e88bd29e7fa2c4552e2804a0ff1ba6db74;hb=HEAD), if we run gettext on it:

```
xgettext -k_ --no-wrap src/bin/initdb/initdb.c ...
````

This will make the msgid and msgstr to not be wrapped at all, but the file occurences will be wrapped at 79 characters (more on this value later).

Some entry examples:

````shell
#: src/bin/initdb/initdb.c:788 src/bin/initdb/initdb.c:795
#: src/bin/initdb/initdb.c:804
#, c-format
msgid ""
"This might mean you have a corrupted installation or identified\n"
"the wrong directory with the invocation option -L.\n"
msgstr ""
````

(occurences wrapped at 79)

````shell
#: src/bin/initdb/initdb.c:2269
#, c-format
msgid "  -N, --no-sync             do not wait for changes to be written safely to disk\n"
msgstr ""
````

(long msgid, not wrapped, 91 characters long)

This happens because when gettext builds the entry, [it calls different functions for each part in write-po.c](https://git.savannah.gnu.org/cgit/gettext.git/tree/gettext-tools/src/write-po.c):

```c
/* Print translator comment if available.  */
  message_print_comment (mp, stream);

  /* Print xgettext extracted comments.  */
  message_print_comment_dot (mp, stream);

  /* Print the file position comments.  This will help a human who is
     trying to navigate the sources.  There is no problem of getting
     repeated positions, because duplicates are checked for.  */
  message_print_comment_filepos (mp, stream, charset, uniforum, page_width);

  /* Print flag information in special comment.  */
  message_print_comment_flags (mp, stream, debug);

  /* Print the previous msgid.  This helps the translator when the msgid has
     only slightly changed.  */
  begin_css_class (stream, class_previous_comment);
  if (mp->prev_msgctxt != NULL)
    wrap (mp, stream, "#| ", 0, class_previous, "msgctxt", mp->prev_msgctxt,
          mp->do_wrap, page_width, charset);
```

As you can see, the message_print_comment, message_print_comment_dot and message_print_comment_flags functions don't take the page_width variable into account so no wrapping is made in those cases, no matter the options or flags.

message_print_comment_filepos does take the page_width but doesn't check for the --no-wrap flag, so it does wrapping whether you like it or not.

The wrap() function takes the page_width parameter but does check if the --no-wrap flag was specified and acts accordingly.

The default 79 characters value comes from [the configure.ac file in gettext source](https://git.savannah.gnu.org/cgit/gettext.git/tree/gettext-tools/configure.ac):

```c
/* This is the page width for the message_print function.  It should
   not be set to more than 79 characters (Emacs users will appreciate
   it).  It is used to wrap the msgid and msgstr strings, and also to
   wrap the file position (#:) comments.  */
#define PAGE_WIDTH 79
```

Since the PostgreSQL .po files are built with the --no-wrap flag I had to make a little workaround on my local copy of polib so it doesn't give me undesired diffs every time I commit (polib.py:1022):

```python
occ_wrapwidth = 79 if wrapwidth == 0 else wrapwidth
if occ_wrapwidth > 0 and len(filestr) + 3 > occ_wrapwidth:
    # textwrap split words that contain hyphen, this is not
    # what we want for filenames, so the dirty hack is to
    # temporally replace hyphens with a char that a file cannot
    # contain, like "*"
    ret += [line.replace('*', '-') for line in textwrap.wrap(
        filestr.replace('-', '*'),
        occ_wrapwidth,
        initial_indent='#: ',
        subsequent_indent='#: ',
        break_long_words=False
    )]
else:
    ret.append('#: ' + filestr)
```

So when I work with polib.pofile(file, wrapwidth=0) I get the desired result ('--no-wrap'-like behaviour)

It's probably not the best solution since because of this gettext behaviour you can do weird stuff like using the -w option along with the --no-wrap flag, e.g.:

```
xgettext -k_ -w50 --no-wrap src/bin/initdb/initdb.c ...
````

This will result on only the occurences being wrapped at 50 characters, the rest is left unwrapped.

I'm not sure if you want to implement this behaviour in polib but if you want I can work on a pull request. Maybe using "-1" as the workaround value, or a new flag, idk.
